# Generated by Django 3.2.20 on 2023-07-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lane',
            name='vehicle_count',
        ),
        migrations.AlterField(
            model_name='lane',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='VehicleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('vehicle_count', models.IntegerField()),
                ('car_count', models.IntegerField()),
                ('bike_count', models.IntegerField()),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.lane')),
            ],
        ),
    ]
