# Generated by Django 3.2.20 on 2023-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20230704_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='truck',
            field=models.IntegerField(default=0),
        ),
    ]
