# Generated by Django 3.2.20 on 2023-07-04 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_lane_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lane',
            name='bike_count',
        ),
        migrations.RemoveField(
            model_name='lane',
            name='car_count',
        ),
        migrations.RemoveField(
            model_name='lane',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='lane',
            name='vehicle_count',
        ),
        migrations.AddField(
            model_name='lane',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LaneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_count', models.IntegerField(default=0)),
                ('car_count', models.IntegerField(default=0)),
                ('bike_count', models.IntegerField(default=0)),
                ('truck_count', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.lane')),
            ],
        ),
    ]
