# Generated by Django 3.2.20 on 2023-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_auto_20230704_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanedata',
            name='green_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lanedata',
            name='red_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lanedata',
            name='yellow_duration',
            field=models.FloatField(default=3),
        ),
    ]
