# Generated by Django 3.2.20 on 2023-07-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_auto_20230704_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanedata',
            name='green_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lanedata',
            name='red_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lanedata',
            name='yellow_duration',
            field=models.IntegerField(default=3),
        ),
    ]
