# Generated by Django 2.1.15 on 2023-07-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_auto_20230705_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lanedata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
