# Generated by Django 2.1.15 on 2023-08-12 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_auto_20230707_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanedata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
