# Generated by Django 2.1.15 on 2023-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0010_auto_20230812_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanedata',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
